### ISSUE TITLE
How can I correctly scale the features to 0 mean and unit variance?

### ISSUE THREAD

**Issue by lishengjie5211** [jpeyre/unrel#6]
Hello, some errors occur in the Matlab code as : 
  features = features - scaler.mu;
  features = features./scaler.std;

Because the size of features is 60760x6, and the size of scale.mu  is 1x6.

When running populate_spatialfeats.m,
Error in apply_gmm (line 4)
  features = features - scaler.mu;
  features = features./scaler.std;

How can I correctly scale the features to 0 mean and unit variance?

Thanks in advance.

**Comment by jpeyre** [comment]
Hi lishengjie5211, 
I guess you are using an older version of matlab which does not allow broadcasting (I am using 2016b). 
scale.mu and scale.std are shared by all instances, so you could replace line 4 and 5 by:
features = features - ones(size(features,1),1)*scaler.mu
features = features ./ (ones(size(features,1),1)*scaler.std)

**Comment by lishengjie5211** [comment]
Your guess is right. It works. Thanks for your quick reply.
