### ISSUE TITLE
Question about Matrix dimensions

### ISSUE THREAD

**Issue by Robinxin123** [jpeyre/unrel#8]
hello jpeyre,
i got some problems, when i ran demo.m. There is a mistake:
![bildschirmfoto vom 2018-11-20 17-20-25](https://user-images.githubusercontent.com/32902208/48787219-a9caad00-ece8-11e8-9aeb-fc76a17ac1ea.png)

after check i found the dimension for features is 7638 X 1000, but for W is 1001X 70. Is there something wrong with W? why here W isn't 1000 X 70.
![bildschirmfoto vom 2018-11-20 17-21-59](https://user-images.githubusercontent.com/32902208/48787329-d7175b00-ece8-11e8-8509-3f41fb30a36b.png)

![bildschirmfoto vom 2018-11-20 17-41-16](https://user-images.githubusercontent.com/32902208/48788669-966d1100-eceb-11e8-8dfe-8b5b6f3a1ebd.png)

many thanks

**Comment by jpeyre** [comment]
Hi Robinxin123, 
I don't know which W you are using exactly, but I guess that your issue come from the fact that you included bias in W and not in the features X. Check whether you have the option "opts.bias" activated, and if this is the case, you should add a column of 1 in the X matrix of features : features  = cat(2,features, opts.bias*ones(size(features,1),1));
You can check the code predict.m or train.m to see how bias is added.

**Comment by Robinxin123** [comment]
Hi jpeyre,
thanks for reply, i have solved it.but now i got another problem with vl_pr().
![bildschirmfoto vom 2018-11-27 10-40-22](https://user-images.githubusercontent.com/32902208/49076874-47b6fe00-f23a-11e8-9e19-07a8e3cca144.png)
it looks like the dimension between recall and precision not agree,but we don't use the two argument (recall , precision) the compute_ap.m. we ignore this two argument with the tilde (~).

Thank you in advance.

**Comment by jpeyre** [comment]
Hi Robinxin123,
Please try to strictly follow the steps in demo.m and the code will run fine. 
It's complicated for me to help you further because I don't know what instructions you are running exactly.

**Comment by Robinxin123** [comment]
ok, i try it , thank you.
